import { NextRequest } from "next/server";
import { z } from "zod";
import { db } from "@/config/db";
import { assets, files } from "@/db/media";
import { eq, and } from "drizzle-orm";
import { withErrorHandler } from "@/lib/helpers/withErrorHandler";
import { requireAuthPublicId } from "@/lib/auth/utils";
import { generateSignature } from "@/lib/services/cloudinary.service";
import { env } from "@/config/env";
import { users } from "@/db/app";
import { ASSET_TYPES, AssetType } from "@/constants/db/media.const";

const ASSET_TYPE_VALUES = Object.values(ASSET_TYPES) as [AssetType, ...AssetType[]];

const prepareItemSchema = z.object({
  id: z.string(), // Local ID generated by the client to map responses
  fileHash: z.string().length(64),
  assetType: z.enum(ASSET_TYPE_VALUES),
  originalFileName: z.string(),
  mimeType: z.string(),
  sizeBytes: z.number().int().positive(),
  description: z.string().optional(),
});

const prepareSchema = z.object({
  items: z.array(prepareItemSchema).min(1).max(50),
});

export const POST = withErrorHandler(async (req: NextRequest) => {
  const userPublicId = await requireAuthPublicId();

  // Find user internal ID
  const user = await db.query.users.findFirst({
    where: eq(users.publicId, userPublicId),
    columns: { id: true },
  });

  if (!user) throw new Error("User not found");

  const body = await req.json();
  const { items } = prepareSchema.parse(body);

  const results = [];

  for (const item of items) {
    // Check if asset exists
    const existingAsset = await db.query.assets.findFirst({
      where: and(eq(assets.fileHash, item.fileHash), eq(assets.assetType, item.assetType)),
    });

    if (existingAsset) {
      // Asset exists! Deduplicate and immediately create the file record.
      const [newFile] = await db
        .insert(files)
        .values({
          assetId: existingAsset.id,
          uploadedBy: user.id,
          originalFileName: item.originalFileName,
          description: item.description,
        })
        .returning();

      results.push({
        id: item.id,
        status: "EXISTS",
        fileId: newFile.id,
        url: existingAsset.cloudinaryUrl,
      });
    } else {
      // Need to upload. Generate signature.
      const folder = `${env.CLOUDINARY_FOLDER}/${item.assetType}`;
      const uploadParams = generateSignature(folder, item.originalFileName);

      results.push({
        id: item.id,
        status: "UPLOAD_REQUIRED",
        uploadParams,
      });
    }
  }

  return { data: { results } };
});
